#include "gbafe.h"
#include "niniandisp.h"

struct ProcCmd const ProcScr_NinianAppearfx[] = {
    PROC_YIELD,
    PROC_CALL(NinianAppear_Init),
    PROC_CALL(NinianAppear_Anim1),
    PROC_REPEAT(NinianAppear_LoopAnim1),
    PROC_CALL(NinianAppear_EndAnim1),
    PROC_CALL(NinianAppear_Anim2),
    // PROC_REPEAT(NinianAppear_LoadUnit),
    PROC_WHILE(CheckBmBgfxDone),
    PROC_CALL(NinianAppear_End),
    PROC_END,
};

const struct BmBgxConf BmBgfxConf_NinianDisp[] = {
    {
        .type = BMFX_CONFT_PAL,
        .data = gUnk_081AD68C,
        .size = 0x0001,
        .duration = 0,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081AD6AC,
        .size = 0x1000,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081ADE60,
        .size = 0x1000,
        .duration = 0,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE528,
        .size =      0,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE64C,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE770,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE894,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_LOOP_START,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE770,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE64C,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE528,
        .size =      0,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE64C,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE770,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE894,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_LOOP,
        .duration = 255,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AE9B8,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AEADC,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081AEC00,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081AED24,
        .size = 0x1000,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081AF718,
        .size = 0x1000,
        .duration = 0,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B0044,
        .size =      0,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B0168,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B028C,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B03B0,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B04D4,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081B05F8,
        .size = 0x1000,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081B10CC,
        .size = 0x1000,
        .duration = 0,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B1660,
        .size =      0,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B1784,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B18A8,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081B19CC,
        .size = 0x1000,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081B23C8,
        .size = 0x1000,
        .duration = 0,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B2AD8,
        .size =      0,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B2BFC,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B2D20,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081B2E44,
        .size = 0x1000,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_ZIMG,
        .data = gUnk_081B36D8,
        .size = 0x1000,
        .duration = 0,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B3A88,
        .size =      0,
        .duration = 1,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B3BAC,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_TSA,
        .data = gUnk_081B3CD0,
        .size =      0,
        .duration = 2,
    },
    {
        .type = BMFX_CONFT_END,
    },
};
