name: Build Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install deps
      run: |
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-arm-none-eabi gcc-arm-none-eabi build-essential cmake
        sudo apt-get install -y re2c ghc cabal-install libghc-vector-dev libghc-juicypixels-dev
        sudo apt-get install -y python3-pip pkg-config libpng* bsdiff moreutils
        pip install pyelftools PyInstaller tmx six
        cabal update

    - name: Install DEVKITPRO
      run: |
        curl -L -o devkit.gz https://github.com/MokhaLeee/fe8_hacks_sundries/releases/download/ci/devkit.gz
        tar -xzvf devkit.gz -C $HOME/

        echo "DEVKITPRO=$HOME/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=\${DEVKITPRO}/devkitARM" >> $GITHUB_ENV
        echo "DEVKITPPC=\${DEVKITPRO}/devkitPPC" >> $GITHUB_ENV
        echo "\${DEVKITPRO}/tools/bin" >> $GITHUB_PATH

    - name: Install submodules
      run: |
        git clone https://github.com/MokhaLeee/FE-CLib-Mokha.git tools/FE-CLib-Mokha
        git clone https://github.com/StanHash/FE-PyTools.git --recursive tools/FE-PyTools
        git clone https://github.com/StanHash/EventAssembler.git --recursive tools/EventAssembler

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Build EA
      run: |
        cd tools/EventAssembler && ./build.sh && cd ../..

    - name: Fake generate baserom
      run: head -c 16M /dev/urandom > fe8.gba

    - name: Build
      run: make all
