name: Build Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build tools
      run: sudo ./Tools/build-tools.sh

    - name: Fake generate baserom
      run: head -c 16M /dev/urandom > fe8.gba

    - name: Build
    - run: make all
    shell: bash
