name: Build Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get -y install binutils-arm-none-eabi gcc-arm-none-eabi build-essential cmake re2c ghc cabal-install libghc-vector-dev libghc-juicypixels-dev python3-pip pkg-config libpng* bsdiff moreutils
        pip install pyelftools PyInstaller tmx six

    - name: Install DEVKITPRO
      run: |
        curl https://github.com/MokhaLeee/fe8_hacks_sundries/releases/download/ci/devkit.gz
        tar -xzvf devkit.gz -C $HOME/

        echo "DEVKITPRO=$HOME/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=\${DEVKITPRO}/devkitARM" >> $GITHUB_ENV
        echo "DEVKITPPC=\${DEVKITPRO}/devkitPPC" >> $GITHUB_ENV
        echo "\${DEVKITPRO}/tools/bin" >> $GITHUB_PATH

    - name: Install submodules
      run: |
        git clone https://github.com/MokhaLeee/FE-CLib-Mokha.git tools/FE-CLib-Mokha
        git clone https://github.com/StanHash/FE-PyTools.git --recursive tools/FE-PyTools
        git clone https://github.com/StanHash/EventAssembler.git --recursive tools/EventAssembler

    - name: Install NET
      run: |
        wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
        chmod +x ./dotnet-install.sh
        sudo ./dotnet-install.sh --channel 6.0

        echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
        echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Build EA
      run: cd tools/EventAssembler && ./build.sh && cd -

    - name: Fake generate baserom
      run: head -c 16M /dev/urandom > fe8.gba

    - name: Build
      run: make all
