name: C Code Style Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install clang-format

    - name: Collect c files
      id: find_modified_files
      run: |
        MODIFIED_FILES=$(git diff --name-only --diff-filter=AM origin/main...HEAD | grep '\.c$' || true)
        echo "Modified C files: $MODIFIED_FILES"
        echo "::set-output name=files::$MODIFIED_FILES"

    - name: Run clang-format on modified files
      if: steps.find_modified_files.outputs.files != ''
      run: |
        for file in $(echo "${{ steps.find_modified_files.outputs.files }}"); do
          echo "Formatting $file"
          clang-format -style=file -i "$file"
        done

    - name: Check for unformatted code
      run: |
        git diff --exit-code
      shell: bash
