name: CI test

on:
  workflow_dispatch:

jobs:
  Build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get -y install binutils-arm-none-eabi gcc-arm-none-eabi build-essential cmake re2c ghc cabal-install libghc-vector-dev libghc-juicypixels-dev python3-pip pkg-config libpng* bsdiff moreutils
        pip install pyelftools PyInstaller tmx six

    - name: Install submodules
      run: |
        git clone https://github.com/StanHash/EventAssembler.git --recursive tools/EventAssembler

    - name: Install NET
      run: |
        wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
        chmod +x ./dotnet-install.sh
        sudo ./dotnet-install.sh --channel 6.0

        echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
        echo "$HOME/.dotnet" >> $GITHUB_PATH
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Build EA
      run: |
        cd tools/EventAssembler && ./build.sh && cd ../..

    - name: test
      run: |
        ./tools/EventAssembler/ColorzCore
