name: CI test

on:
  workflow_dispatch:

jobs:
  Build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-arm-none-eabi gcc-arm-none-eabi build-essential cmake
        sudo apt-get install -y re2c ghc cabal-install libghc-vector-dev libghc-juicypixels-dev
        sudo apt-get install -y python3-pip pkg-config libpng* bsdiff moreutils
        pip install pyelftools PyInstaller tmx six
        cabal update

    - name: Install submodules
      run: |
        git clone https://github.com/StanHash/EventAssembler.git --recursive tools/EventAssembler

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: test dotnet
      run: dotnet --version

    - name: test babal
      run: |
        cd tools/EventAssembler/.Sources/EAFormattingSuite
        cabal v1-install --bindir=../../Tools
